
# environment parameters =======================================================
t_kelvin = 296.15
com_to_stacking = 0.34
com_to_hb = 0.4
com_to_backbone = -0.4
hb_weights_sa = [
    [0.0, 0.0, 0.0, 1.0],  # AX
    [0.0, 0.0, 1.0, 0.0],  # CX
    [0.0, 1.0, 0.0, 0.0],  # GX
    [1.0, 0.0, 0.0, 0.0],  # TX
]
stack_weights_sa = [
    [1.0, 1.0, 1.0, 1.0],  # AX
    [1.0, 1.0, 1.0, 1.0],  # CX
    [1.0, 1.0, 1.0, 1.0],  # GX
    [1.0, 1.0, 1.0, 1.0],  # TX
]

# bonded parameters ============================================================

[bonded_excluded_volume]
eps_exc = 2.0
dr_star_base = 0.32
sigma_base = 0.33
sigma_back_base  = 0.515
sigma_base_back = 0.515
dr_star_back_base = 0.50
dr_star_base_back = 0.50

[vfene]
eps_backbone = 2.0
r0_backbone = 0.7525
delta_backbone = 0.25
fmax = 500.0
finf = 4.0

[stacking]
dr_low_stack = 0.32
dr_high_stack = 0.75
eps_stack = 1.3448
a_stack = 6.0
dr0_stack = 0.4
dr_c_stack = 0.9
theta0_stack_4 = 0.0
delta_theta_star_stack_4 = 0.8
a_stack_4 = 1.30
theta0_stack_5 = 0.0
delta_theta_star_stack_5 = 0.95
a_stack_5 = 0.90
theta0_stack_6 = 0.0
delta_theta_star_stack_6 = 0.95
a_stack_6 = 0.90
neg_cos_phi1_star_stack = -0.65
a_stack_1 = 2.00
neg_cos_phi2_star_stack = -0.65
a_stack_2 = 2.00

# unbonded parameters ==========================================================

[unbonded_excluded_volume]
eps_exc = 2.0
dr_star_base = 0.32
sigma_base = 0.33
dr_star_back_base = 0.50
sigma_back_base = 0.515
dr_star_base_back = 0.50
sigma_base_back = 0.515
dr_star_backbone = 0.675
sigma_backbone = 0.70

[hydrogen_bonding]
dr_low_hb = 0.34
dr_high_hb = 0.70
eps_hb = 1.077
a_hb = 8.0
dr0_hb = 0.4
dr_c_hb = 0.75
theta0_hb_1 = 0.0
delta_theta_star_hb_1 = 0.70
a_hb_1 = 1.50
theta0_hb_2 = 0.0
delta_theta_star_hb_2 = 0.70
a_hb_2 = 1.50
theta0_hb_3 = 0.0
delta_theta_star_hb_3 = 0.70
a_hb_3 = 1.50
theta0_hb_4 = "pi"
delta_theta_star_hb_4 = 0.70
a_hb_4 = 0.46
theta0_hb_7 = "pi / 2"
delta_theta_star_hb_7 = 0.45
a_hb_7 = 4.0
theta0_hb_8 = "pi / 2"
delta_theta_star_hb_8 = 0.45
a_hb_8 = 4.0

[cross_stacking]
dr_low_cross = 0.495
dr_high_cross = 0.655
k_cross = 47.5
r0_cross = 0.575
dr_c_cross = 0.675
theta0_cross_1 = "pi - 2.35"
delta_theta_star_cross_1 = 0.58
a_cross_1 = 2.25
theta0_cross_2 = 1.00
delta_theta_star_cross_2 = 0.68
a_cross_2 = 1.70
theta0_cross_3 = 1.00
delta_theta_star_cross_3 = 0.68
a_cross_3 = 1.70
theta0_cross_4 = 0.0
delta_theta_star_cross_4 = 0.65
a_cross_4 = 1.50
theta0_cross_7 = 0.875
delta_theta_star_cross_7 = 0.68
a_cross_7 = 1.70
theta0_cross_8 = 0.875
delta_theta_star_cross_8 = 0.68
a_cross_8 = 1.70

[coaxial_stacking]
dr_low_coax = 0.22
dr_high_coax = 0.58
k_coax = 46.0
dr0_coax = 0.4
dr_c_coax = 0.6
theta0_coax_4 = 0.0
delta_theta_star_coax_4 = 0.8
a_coax_4 = 1.30
theta0_coax_1 = "pi - 0.60"
delta_theta_star_coax_1 = 0.65
a_coax_1 = 2.00
theta0_coax_5 = 0.0
delta_theta_star_coax_5 = 0.95
a_coax_5 = 0.90
theta0_coax_6 = 0.0
delta_theta_star_coax_6 = 0.95
a_coax_6 = 0.90
cos_phi3_star_coax = -0.65
a_coax_3p = 2.0
cos_phi4_star_coax = -0.65
a_coax_4p = 2.0

