
[geometry]
pos_stack = 0.34
pos_base = 0.4

pos_back_a1 = -0.4
pos_back_a3 = 0.2
pos_back_a2 = 0.0

pos_stack_3_a1 = 0.4
pos_stack_3_a2 = 0.1
pos_stack_5_a1 =  0.124906078525
pos_stack_5_a2 = -0.00866274917473



p5_x = -0.104402
p5_y = -0.841783
p5_z = 0.529624
p3_x = -0.462510
p3_y = -0.528218
p3_z = 0.712089

# bonded parameters ============================================================

[fene]
eps_backbone = 2.0
r0_backbone =  0.761070781051
delta_backbone = 0.25
fmax = 500.0
finf = 4.0


[bonded_excluded_volume]
eps_exc = 2.0
dr_star_base = 0.32
sigma_base = 0.33
sigma_back_base = 0.515
sigma_base_back = 0.515
dr_star_back_base = 0.50
dr_star_base_back = 0.50


[stacking]

## f1(dr_stack)
eps_stack_base = 1.40206
eps_stack_kt_coeff = 2.77
a_stack = 6.0
dr0_stack = 0.43
dr_c_stack = 0.93
dr_low_stack = 0.35
dr_high_stack = 0.78

## f4(theta_5p)
a_stack_5 = 0.90
theta0_stack_5 = 0.0
delta_theta_star_stack_5 = 0.95

## f4(theta_6p)
a_stack_6 = 0.90
theta0_stack_6 = 0.0
delta_theta_star_stack_6 = 0.95

## f4(theta_9)
a_stack_9 = 1.3
theta0_stack_9 = 0.0
delta_theta_star_stack_9 = 0.8

## f4(theta_10)
a_stack_10 = 1.3
theta0_stack_10 = 0.0
delta_theta_star_stack_10 = 0.8

## f5(-cos(phi1))
a_stack_1 = 2.00
neg_cos_phi1_star_stack = -0.65

## f5(-cos(phi2))
a_stack_2 = 2.00
neg_cos_phi2_star_stack = -0.65



# unbonded parameters ==========================================================

[unbonded_excluded_volume]
eps_exc = 2.0
dr_star_base = 0.32
sigma_base = 0.33
dr_star_back_base = 0.50
sigma_back_base = 0.515
dr_star_base_back = 0.50
sigma_base_back = 0.515
dr_star_backbone = 0.675
sigma_backbone = 0.70


[hydrogen_bonding]

## f1(dr_hb)
eps_hb = 0.870439
a_hb = 8.0
dr0_hb = 0.4
dr_c_hb = 0.75
dr_low_hb = 0.34
dr_high_hb = 0.70

## f4(theta_1)
a_hb_1 = 1.50
theta0_hb_1 = 0.0
delta_theta_star_hb_1 = 0.70

## f4(theta_2)
a_hb_2 = 1.50
theta0_hb_2 = 0.0
delta_theta_star_hb_2 = 0.70

## f4(theta_3)
a_hb_3 = 1.50
theta0_hb_3 = 0.0
delta_theta_star_hb_3 = 0.70

## f4(theta_4)
a_hb_4 = 0.46
theta0_hb_4 = "pi"
delta_theta_star_hb_4 = 0.70

## f4(theta_7)
a_hb_7 = 4.0
theta0_hb_7 = "pi / 2"
delta_theta_star_hb_7 = 0.45

## f4(theta_8)
a_hb_8 = 4.0
theta0_hb_8 = "pi / 2"
delta_theta_star_hb_8 = 0.45


[cross_stacking]

## f2(dr_cross)
k_cross = 59.9626
r0_cross = 0.5
dr_c_cross = 0.6
dr_low_cross = 0.42
dr_high_cross = 0.58

## f4(theta_1)
a_cross_1 = 2.25
theta0_cross_1 = 0.505
delta_theta_star_cross_1 = 0.58

## f4(theta_2)
a_cross_2 = 1.70
theta0_cross_2 = 1.266
delta_theta_star_cross_2 = 0.68

## f4(theta_3)
a_cross_3 = 1.70
theta0_cross_3 = 1.266
delta_theta_star_cross_3 = 0.68

## f4(theta_7) + f4(pi - theta_7)
a_cross_7 = 1.70
theta0_cross_7 = 0.309
delta_theta_star_cross_7 = 0.68

## f4(theta_8) + f4(pi - theta_8)
a_cross_8 = 1.70
theta0_cross_8 = 0.309
delta_theta_star_cross_8 = 0.68

# Coaxial Stacking
[coaxial_stacking]

## f2(dr_coax)
k_coax = 80.0
dr0_coax = 0.5
dr_c_coax = 0.6
dr_low_coax = 0.42
dr_high_coax = 0.58

## f4(theta_4)
a_coax_4 = 1.30
theta0_coax_4 = 0.151
delta_theta_star_coax_4 = 0.8

## f4(theta_1) + f4(2*pi - theta_1)
a_coax_1 = 2.00
theta0_coax_1 = 2.592
delta_theta_star_coax_1 = 0.65

## f4(theta_5) + f4(pi - theta_5)
a_coax_5 = 0.90
theta0_coax_5 = 0.685
delta_theta_star_coax_5 = 0.95

## f4(theta_6) + f4(pi - theta_6)
a_coax_6 = 0.90
theta0_coax_6 = 0.685
delta_theta_star_coax_6 = 0.95

## f5(cos(phi3))
a_coax_3p = 2.0
cos_phi3_star_coax = -0.65

## f5(cos(phi4))
a_coax_4p = 2.0
cos_phi4_star_coax = -0.65

[debye]
q_eff = 1.26
lambda_factor = 0.3667258
prefactor_coeff = 0.05404383975812547